
# A failing test throws an error
def failing_test():
    # 1+'f'
    # assert False
    # assert 1=2    
    pass
